package entity;
// Generated Jun 8, 2018 1:41:49 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Tregister generated by hbm2java
 */

public class Tregister implements java.io.Serializable {

    private int id;
    private String name;
    private String lastname;
    private String email;
    private int age;
    private String phone;
    private Date registerDate;
    private Date lastLogin;
    private String username;
    private String password;

    public Tregister() {
    }

    public Tregister(int id, String name, String lastname, String email, int age, String phone, Date registerDate, Date lastLogin, String username, String password) {
        this.id = id;
        this.name = name;
        this.lastname = lastname;
        this.email = email;
        this.age = age;
        this.phone = phone;
        this.registerDate = registerDate;
        this.lastLogin = lastLogin;
        this.username = username;
        this.password = password;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getAge() {
        return this.age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Date getRegisterDate() {
        return this.registerDate;
    }

    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    public Date getLastLogin() {
        return this.lastLogin;
    }

    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
